services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: jsaa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
